### ISSUE TITLE
插件很好！但总是无缘无故“闪退”！求大佬检查一下！

### ISSUE THREAD

**Issue by hillsmao** [sethyuan/logseq-plugin-smart-typing#1]
这个插件简直是我block-ref党的福音，大大提高了我做footnote `[]((()))`的便利！

但是，总是无缘无故的不起作用。

打开插件设置，smart typing也消失了，找不到。
打开插件市场，smart typing又是安装了的。

只要把插件启用开关——关上，在打开。功能又恢复了。

求大佬再检查一下！

**Comment by sethyuan** [comment]
能贴一个你的插件配置上来看看是什么样的吗？另外如果有console截图就更方便排查了。`ctrl+shift+i` 打开console，macOS的话是`cmd+shift+i`

**Comment by hillsmao** [comment]
<img width="666" alt="image" src="https://user-images.githubusercontent.com/107061250/218693600-83478a7a-138d-47ac-ae0b-b68bc931639c.png">
<img width="617" alt="image" src="https://user-images.githubusercontent.com/107061250/218693670-96739934-adea-43fc-9963-d6391a6fa5f8.png">

**Comment by hillsmao** [comment]
<img width="1438" alt="image" src="https://user-images.githubusercontent.com/107061250/218694078-140c5357-c586-409c-bb19-509b13b9bd7f.png">

**Comment by hillsmao** [comment]
lsplugin.core.js:2 Object
core.cljs:193 restore-tokens-from-localstorage
core.cljs:56 
    Welcome to Logseq!
    If you encounter any problem, feel free to file an issue on GitHub (https://github.com/logseq/logseq)
    or join our forum (https://discuss.logseq.com).
    .____
    |    |    ____   ____  ______ ____  ______
    |    |   /  _ \ / ___\/  ___// __ \/ ____/
    |    |__(  <_> ) /_/  >___ \\  ___< <_|  |
    |_______ \____/\___  /____  >\___  >__   |
            \/    /_____/     \/     \/   |__|
     
index.ee1e9d84.js:2 plugin loaded
index.2869ea90.js:2 logseq-helium-plugin loaded
index.e842b591.js:50 #logseq-readwise-official-plugin: MAIN
index.92b35697.js:54 #logseq-tabs: MAIN
index.92b35697.js:59 #logseq-tabs: MAIN DONE
index.71d9e3fd.js:595 #doc loaded
index.e44bd72e.js:5495 #tocgen loaded
index.dcf580dd.js:11613 TypeError: Cannot read properties of null (reading 'flat')
    at fetchFutureReminders (index.dcf580dd.js:11611:92)
    at async initReminders (index.dcf580dd.js:11600:29)
    at async Jt.main (index.dcf580dd.js:11543:5)
fetchFutureReminders @ index.dcf580dd.js:11613
index.dcf580dd.js:11597 #reminder loaded
index.07dd723b.js:5827 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'map')
    at reloadUserFns (index.07dd723b.js:5827:31)
    at async Co.main (index.07dd723b.js:6116:5)
bundle.4a311.js:1 #batch-op loaded
index.a68bfebd.js:1 [Inbox Telegram] Started!
index.a68bfebd.js:1 [Inbox Telegram] Polling started!
index.53009533.js:176 #ol loaded
index.13da3edc.js:2 logseq-psummarise-plugin loaded
index.64896440.js:2 Swap plugin loaded.
index.e596f686.js:144 #logseq-todo-master: MAIN
index.e596f686.js:144 #logseq-todo-master: MAIN DONE
index.e984101b.js:1 Wordcount plugin loaded
index.e842b591.js:82 Auto sync loaded.
instrument.js:191 :debug "set-token-to-localstorage!"
instrument.js:191 db restored, setting up repo hooks
instrument.js:191 reloading custom.css
index.e842b591.js:50 Starting sync...
index.e842b591.js:50 null
instrument.js:191 [interact.js] Consider adding CSS "touch-action: none" to this element
 <div role=​"separator" data-expanded=​"true" tabindex=​"0" aria-valuemax=​"70" class=​"resizer" aria-orientation=​"vertical" aria-label=​"调整右侧边栏大小" aria-valuemin=​"10" aria-valuenow=​"0.431245">​</div>​ https://developer.mozilla.org/en-US/docs/Web/CSS/touch-action
(anonymous) @ instrument.js:191
instrument.js:191 D:Search > Transact blocks!: logseq_local_/Users/Narcissus/Downloads/loggit
instrument.js:191 D:Search > Transact pages!: logseq_local_/Users/Narcissus/Downloads/loggit
instrument.js:191 D:Search > Transact blocks!: logseq_local_/Users/Narcissus/Downloads/loggit
instrument.js:191 D:Search > Transact pages!: logseq_local_/Users/Narcissus/Downloads/loggit
instrument.js:191 D:Search > Transact blocks!: logseq_local_/Users/Narcissus/Downloads/loggit
instrument.js:191 D:Search > Transact pages!: logseq_local_/Users/Narcissus/Downloads/loggit
instrument.js:191 D:Search > Transact blocks!: logseq_local_/Users/Narcissus/Downloads/loggit
instrument.js:191 D:Search > Transact pages!: logseq_local_/Users/Narcissus/Downloads/loggit
instrument.js:191 D:Search > Transact blocks!: logseq_local_/Users/Narcissus/Downloads/loggit
instrument.js:191 D:Search > Transact pages!: logseq_local_/Users/Narcissus/Downloads/loggit
index.07dd723b.js:6252 #smart-typing loaded
instrument.js:191 D:Search > Transact blocks!: logseq_local_/Users/Narcissus/Downloads/loggit
instrument.js:191 D:Search > Transact pages!: logseq_local_/Users/Narcissus/Downloads/loggit
instrument.js:191 D:Search > Transact blocks!: logseq_local_/Users/Narcissus/Downloads/loggit
instrument.js:191 D:Search > Transact pages!: logseq_local_/Users/Narcissus/Downloads/loggit
instrument.js:191 D:Search > Transact pages!: logseq_local_/Users/Narcissus/Downloads/loggit
instrument.js:191 D:Search > Transact blocks!: logseq_local_/Users/Narcissus/Downloads/loggit
instrument.js:191 D:Search > Transact pages!: logseq_local_/Users/Narcissus/Downloads/loggit
instrument.js:191 D:Search > Transact pages!: logseq_local_/Users/Narcissus/Downloads/loggit
instrument.js:191 D:Search > Transact blocks!: logseq_local_/Users/Narcissus/Downloads/loggit
instrument.js:191 D:Search > Transact pages!: logseq_local_/Users/Narcissus/Downloads/loggit
instrument.js:191 D:Search > Transact blocks!: logseq_local_/Users/Narcissus/Downloads/loggit
instrument.js:191 D:Search > Transact pages!: logseq_local_/Users/Narcissus/Downloads/loggit
instrument.js:191 D:Search > Transact blocks!: logseq_local_/Users/Narcissus/Downloads/loggit
instrument.js:191 D:Search > Transact pages!: logseq_local_/Users/Narcissus/Downloads/loggit
instrument.js:191 D:Search > Transact blocks!: logseq_local_/Users/Narcissus/Downloads/loggit
instrument.js:191 D:Search > Transact pages!: logseq_local_/Users/Narcissus/Downloads/loggit
instrument.js:191 D:Search > Transact blocks!: logseq_local_/Users/Narcissus/Downloads/loggit
instrument.js:191 D:Search > Transact pages!: logseq_local_/Users/Narcissus/Downloads/loggit
instrument.js:191 D:Search > Transact blocks!: logseq_local_/Users/Narcissus/Downloads/loggit
instrument.js:191 D:Search > Transact pages!: logseq_local_/Users/Narcissus/Downloads/loggit
instrument.js:191 D:Search > Transact blocks!: logseq_local_/Users/Narcissus/Downloads/loggit
instrument.js:191 D:Search > Transact pages!: logseq_local_/Users/Narcissus/Downloads/loggit
instrument.js:191 D:Search > Transact pages!: logseq_local_/Users/Narcissus/Downloads/loggit
instrument.js:191 D:Search > Transact blocks!: logseq_local_/Users/Narcissus/Downloads/loggit
instrument.js:191 D:Search > Transact pages!: logseq_local_/Users/Narcissus/Downloads/loggit
instrument.js:191 D:Search > Transact blocks!: logseq_local_/Users/Narcissus/Downloads/loggit
instrument.js:191 D:Search > Transact pages!: logseq_local_/Users/Narcissus/Downloads/loggit
instrument.js:191 D:Search > Transact blocks!: logseq_local_/Users/Narcissus/Downloads/loggit
instrument.js:191 D:Search > Transact pages!: logseq_local_/Users/Narcissus/Downloads/loggit
instrument.js:191 D:Search > Transact blocks!: logseq_local_/Users/Narcissus/Downloads/loggit
instrument.js:191 D:Search > Transact pages!: logseq_local_/Users/Narcissus/Downloads/loggit
instrument.js:191 D:Search > Transact pages!: logseq_local_/Users/Narcissus/Downloads/loggit
instrument.js:191 D:Search > Transact pages!: logseq_local_/Users/Narcissus/Downloads/loggit
instrument.js:191 D:Search > Transact pages!: logseq_local_/Users/Narcissus/Downloads/loggit
instrument.js:191 D:Search > Transact blocks!: logseq_local_/Users/Narcissus/Downloads/loggit
instrument.js:191 D:Search > Transact pages!: logseq_local_/Users/Narcissus/Downloads/loggit

**Comment by sethyuan** [comment]
@hillsmao 我更新了一版，再试试看呢。

**Comment by hillsmao** [comment]
目前非常稳定！感谢！
