### ISSUE TITLE
大神！30个也不够用了，求增加数量

### ISSUE THREAD

**Issue by hillsmao** [sethyuan/logseq-plugin-smart-typing#10]

**Comment by sethyuan** [comment]
添加到了50个。😂

**Comment by hillsmao** [comment]
love u!!! 好赞啊这个插件，几乎可以把常用的私有标签、namespace alias 都快捷输入，太优秀了

话说按3个空格是啥意思？看介绍不太懂

**Comment by sethyuan** [comment]
3个空格是用正则表达式来匹配和替换，README里最后一个演示视频就是关于这个功能的介绍，可以看看。
