### ISSUE TITLE
中文输入两个左双括号无法自动补全右括号

### ISSUE THREAD

**Issue by avarbykira** [sethyuan/logseq-plugin-smart-typing#11]
hi，我遇到了类似的问题：中文输入两个左双括号（包括圆括号和方括号）时，无法自动补全右括号。插件和logseq均为最新版本。

这个有解决办法嘛？
![测试 2023-05-29 11-44-34 mp4_20230529_115134](https://github.com/sethyuan/logseq-plugin-smart-typing/assets/52104515/bb7d11ff-f809-4db5-b169-c8e697a75642)

_Originally posted by @avarbykira in https://github.com/sethyuan/logseq-plugin-smart-typing/issues/2#issuecomment-1566473688_

**Comment by sethyuan** [comment]
确实可能会与系统的有冲突，试试把这个从插件配置里关掉呢。
![image](https://github.com/sethyuan/logseq-plugin-smart-typing/assets/3410293/dcbf2f45-03c3-4852-8bcf-f295380999d3)

**Comment by avarbykira** [comment]
还是无法解决，关闭后会出现两个中文括号，如图。
![image](https://github.com/sethyuan/logseq-plugin-smart-typing/assets/52104515/76e714f0-7f15-4692-8201-6470c2fca390)

**Comment by avarbykira** [comment]
还是不行，会显示两个中文括号，如图。
![image](https://github.com/sethyuan/logseq-plugin-smart-typing/assets/52104515/71018eef-a5b6-4b84-b4ec-827a91a8692f)

**Comment by sethyuan** [comment]
你是最新版的Logseq吗？我看我这边关掉后Logseq自身就会替换【【

**Comment by avarbykira** [comment]
![image](https://github.com/sethyuan/logseq-plugin-smart-typing/assets/52104515/a32b96b3-62dd-40e0-82a6-5bbaec90ac7c)
![image](https://github.com/sethyuan/logseq-plugin-smart-typing/assets/52104515/3a8422a9-d08d-4538-98ba-fc033df48e76)
插件和app都是最新的

**Comment by sethyuan** [comment]
我这边把插件关了也是可以自动补完的，Logseq自带的能力。你试试把插件关掉重启Logseq再看看呢。

**Comment by avarbykira** [comment]
还是不行。我就是因为logseq本身无法处理双中文括号才找到的这个插件😭。你说的操作我都做了，包括重启，均没解决问题。

**Comment by sethyuan** [comment]
你是啥操作系统？

**Comment by avarbykira** [comment]
Windows 10

**Comment by sethyuan** [comment]
我是macOS。Windows得等我晚上回去才能看了。

**Comment by avarbykira** [comment]
好的。麻烦了。

**Comment by sethyuan** [comment]
我在我的Windows上也看过了，和macOS上是一样的，输入 `【【` 都可以自动变换成 `[[`。 😂

**Comment by avarbykira** [comment]
还是不行（捂脸 

我的logseq是最新版本，我也去问问官方那边吧。

**Comment by sethyuan** [comment]
好的，感觉你的问题应该和插件无关了，我先把这个ticket关了吧。Smart Typing还有很多强大的功能，欢迎尝试，使用过程中再有什么问题欢迎随时再来提issue。
