### ISSUE TITLE
这个插件看起来好棒！但是weather实现不了，以及公式计算是怎么实现的呀？

### ISSUE THREAD

**Issue by yoghurtdewdew** [sethyuan/logseq-plugin-smart-typing#14]
这个插件看起来也太棒了！
我不太懂编程，我试了weather，发现实现不了：
![image](https://github.com/sethyuan/logseq-plugin-smart-typing/assets/63794438/5aea9890-ac5b-4e49-a0c8-09dfcb2b75d0)
![image](https://github.com/sethyuan/logseq-plugin-smart-typing/assets/63794438/b9f10778-8d16-4d59-a8c2-e16113d333bb)
试了`@weather`和`weather`加空格，被替换的部分试了`{{weather('上海')}}`和`{{weather("上海")}}`以及`{{weather()}}`，都不行诶，没发生任何替换

另外想问下：公式计算是怎么实现的呀？方便展示代码嘛 视频里有点看不清👻，这个可以输入任意公式进行计算吗？比如XX*XXX/XXXX=……

**Comment by yoghurtdewdew** [comment]
<img width="697" alt="image" src="https://github.com/sethyuan/logseq-plugin-smart-typing/assets/63794438/0d0798b5-e384-4cd7-a0e5-ea6b84525568">
<img width="672" alt="image" src="https://github.com/sethyuan/logseq-plugin-smart-typing/assets/63794438/b3fc4518-d404-42b4-a106-6ec2e1cc44e8">
<img width="680" alt="image" src="https://github.com/sethyuan/logseq-plugin-smart-typing/assets/63794438/dd01cfc0-a52b-4b32-9c77-16e6a6599abe">
<img width="652" alt="image" src="https://github.com/sethyuan/logseq-plugin-smart-typing/assets/63794438/d130b8fc-130b-4c02-9602-07664dafedf9">
重启之后还是如上图所示，黄色那个是自己手动敲了一下试试有没有反应 看到没有反应，`weather ` 是我试了下替换 看到没发生替换
我不太懂代码诶，想要继续请教下，这个标签具体要加在哪里，反引号与首行代码放在一起还是单独一行呢，我好菜😅

**Comment by sethyuan** [comment]
![image](https://github.com/sethyuan/logseq-plugin-smart-typing/assets/3410293/c1135ff9-eb2d-4384-9608-8a73b26f084d)

可以参看README中的视频。

**Comment by yoghurtdewdew** [comment]
完蛋大佬，我刚刚，点击插件的⚙-打开配置项，打算设置一下，打开发现是edn文件，就在里面把{{weather(\"上海\")}}改成了{{weather(\'上海\')}}，然后，发现插件好像用不了了，就是之前能用的替换也失效了，然后我想着重新加载一下插件，发现那个开关也关不上了，也点不开配置了，是不是只能重装了 😣 能找到之前的edn文件救一下嘛，在按照位置里面也没找到可以直接编辑的edn文件
<img width="378" alt="image" src="https://github.com/sethyuan/logseq-plugin-smart-typing/assets/63794438/d59a41f7-1e42-48d8-a8d8-34d221cc805e">

**Comment by yoghurtdewdew** [comment]
<img width="567" alt="image" src="https://github.com/sethyuan/logseq-plugin-smart-typing/assets/63794438/e73a7ae0-029f-4858-a68d-5fa481461c80">

<img width="584" alt="image" src="https://github.com/sethyuan/logseq-plugin-smart-typing/assets/63794438/0651fa27-7b7c-4d66-bf40-c7a7899c1c5e">

又重启了下，目前打开配置会这样 😣 咋救

**Comment by sethyuan** [comment]
手动修改前要做好备份，以防万一。插件的配置文件都在你用户文件夹下的 `.logseq/settings`文件夹下。

**Comment by yoghurtdewdew** [comment]
感恩！我找到了js文件把可能造成问题的内容删掉后，插件又能在Logseq里用了，但是`@weather`还是没有反应
<img width="945" alt="image" src="https://github.com/sethyuan/logseq-plugin-smart-typing/assets/63794438/7054367d-bfae-4f15-94cd-ce25e7469e4e">
然后我把代码移动到演示视频中的fns页面，重启，`@weather`还是没有反应
<img width="679" alt="image" src="https://github.com/sethyuan/logseq-plugin-smart-typing/assets/63794438/50b3a502-2515-41a3-b2c0-d38bdf113f84">
<img width="480" alt="image" src="https://github.com/sethyuan/logseq-plugin-smart-typing/assets/63794438/3aa797bd-65e2-4df2-922e-2de58e6775e4">
配置应该没有问题吧，在`@weather`后加一个空格，意味着输入空格时触发，但是这里没有触发

**Comment by sethyuan** [comment]
那有可能是这个API用不了了（本来就是个演示用的key），你试试用其它内容替换看看能不能出来。

**Comment by yoghurtdewdew** [comment]
大佬！我昨晚上去注册了个api，version=v91，替换appid和appsecret里的值，还是没有反应，难道不是api的问题 0.0
但是有点奇怪的是，我替换完随便点击一个地方那个代码就会出现在一个新的block，再点又出来一个，然后我就重启Logseq，然后发现设置的函数还是替换不了

以及，后来我插件打不开设置项了，就是在设置-插件设置里找不到smart type，在插件-打开配置项，只能打开json文件
目前，试了重装Logseq，re-index，开关插件按钮，还是只能打开json文件，之前能用的替换也替换不了了 0.0

**Comment by sethyuan** [comment]
天呢，你都做了什么？把插件卸载了，把 `.logseq/settings` 下对应的插件配置文件也删除掉，重启Logseq看看其它功能都正常不。没问题了再用插件市场重装插件，不要直接修改插件的配置文件，通过界面去设置。

**Comment by yoghurtdewdew** [comment]
插件卸了，`.logseq/settings` 下的`smart-typing`的文件删除了，然后重装插件，`设置-插件设置`菜单里没有，重启Logseq，没有，重启电脑，没有，重启Logseq，没有，卸载插件重装，没有… (挠头.gjf)

**Comment by sethyuan** [comment]
你可以先备份，再尝试清理一下cache看看。
![image](https://github.com/sethyuan/logseq-plugin-smart-typing/assets/3410293/68e01362-c421-46a5-9ad5-b9a23cb22fa8)

**Comment by yoghurtdewdew** [comment]
清理cache真的管用！可以用了！
不过天气函数还是出不来，不知道是哪里的原因，api那个链接我放在浏览器里打开能拉出来数据，但是编程我实在就不懂了 0.0
<img width="1076" alt="image" src="https://github.com/sethyuan/logseq-plugin-smart-typing/assets/63794438/9a4ec888-c715-4250-b3c1-0f78d928895b">
<img width="215" alt="image" src="https://github.com/sethyuan/logseq-plugin-smart-typing/assets/63794438/bf3830b9-ed19-488f-8f63-e7335e1748f5">
然后刷新，然后输入天气空格没反应后，我重启Logseq，然后设置-插件设置里就找不到smart typing了，替换也全都失效了
然后清理cache
设置-插件设置里可以找到smart typing
然后其他替换可用，输入天气空格没反应 0.0
啊 我可真是自讨苦吃，捣鼓半天啥都没捣鼓出来，得亏大佬肯指导我，不然我得捣鼓坏了 0.0
<img width="247" alt="image" src="https://github.com/sethyuan/logseq-plugin-smart-typing/assets/63794438/520cee41-f79b-4603-a7a4-99186d4d1ef0">

**Comment by yoghurtdewdew** [comment]
另外，这样之后，如果刷新页面`⌘ R `，所有替换就又失效了，就又得从清理cache开始 0.0

**Comment by sethyuan** [comment]
你上面的函数写错了，拷贝我之前给出的改。

**Comment by yoghurtdewdew** [comment]
有点不好编辑，代码总是会自动变，特别是，需要在里面替换字符时……
![222](https://github.com/sethyuan/logseq-plugin-smart-typing/assets/63794438/62580ea9-41db-43fc-98f0-7abe7bd57770)

然后，终于，重新弄好后，确认代码没问题后，刷新页面，然后输入设置的字符 天气 或weather ，没有反应，然后重启，神奇的一幕出现了，竟然能用！太神奇了！

但是我不明白，为啥代码总是会自动变来变去的呢，这个大佬有没有遇到这个问题，是咋解决的 0.0

如果我要放多个函数，还是放在`[[fns]]`页面嘛？还是说随便放个什么位置都可以，只要底下带个`#.fn`标签就可以呢？由于我不懂`fns`和`#.fn`啥意思，所以就只能问这么笨的问题了，希望大佬别见怪

感恩大佬不吝赐教！！！！

**Comment by sethyuan** [comment]
只要底下带个#.fn标签就可以。
