### ISSUE TITLE
格式化日期这个功能应该怎么写？

### ISSUE THREAD

**Issue by VandeeFeng** [sethyuan/logseq-plugin-smart-typing#16]
dateFormat(date, formatStr) - 返回格式化的日期，date是一个 JS Date 对象，formatStr是格式化字符串。这个具体应该怎么写啊，比如我想返回一个今天的日期，格式是YYYYMMDD，🙏看了视频实例没学会

**Comment by sethyuan** [comment]
格式化字符串请参考这里的文档：
https://date-fns.org/v2.29.2/docs/format

`new Date()`就是JS中的当前日期+时间。

**Comment by VandeeFeng** [comment]
感谢！

**Comment by VandeeFeng** [comment]
🙏解决了我一个大问题，想插入当前时间的时间戳到笔记，logseq的时间戳没弄明白，我重新建立索引之后，logseq好像用的不是本地文件的创建时间，我是win10。在show page data 里面的 :block/created-at 里的时间还要转换。
