### ISSUE TITLE
In time, add "0" before minutes 1-9 in an hour?

### ISSUE THREAD

**Issue by novakwh** [sethyuan/logseq-plugin-smart-typing#17]
Hi there, this plugin works great, but when I use {{time(false)}} and the time happens to be minute 1-9 within an hour, the 0 is left off of the text that is returned, so the plugin unexpectedly returns something like:

10:1 AM

when the standard format should be:

10:01 AM

Is there a way to fix this? Thank you!

**Comment by novakwh** [comment]
> Thanks for reporting, this is fixed and a new version and released.

Oof, unfortunately, now there is a bigger issue. Updated and inserted the time and here is what came out:

09:947 AM

**Comment by novakwh** [comment]
Also, if it helps, just now at 2:05 PM I inserted the time and it returned the following:

02:25 PM

...so it looks like it is repeating the hour, but still leaving the 0 out of the minute.

**Comment by sethyuan** [comment]
My bad, I typed the format wrong. I have corrected it. Please update and give it a try.

**Comment by novakwh** [comment]
Yes, now the time seems to work great! Thanks so much for this awesome plugin, it makes life a lot easier when using Logseq across multiple operating systems.
