### ISSUE TITLE
中文双括号好像和系统本身冲突

### ISSUE THREAD

**Issue by hillsmao** [sethyuan/logseq-plugin-smart-typing#2]
【【】】
（（））
这两个logseq本身自带的

插件在用的过程中，会出现跳两次，导致出现，括号不全，变多的情况

是不是把这几个系统自带的补全功能禁用了？

**Comment by sethyuan** [comment]
我调了一下发了个新版本，你结合最新的Logseq再试试看呢。

**Comment by hillsmao** [comment]
没问题了！！感谢！这更新也太快了！

**Comment by avarbykira** [comment]
hi，我遇到了类似的问题：中文输入两个左双括号（包括圆括号和方括号）时，无法自动补全右括号。插件和logseq均为最新版本。

这个有解决办法嘛？
![测试 2023-05-29 11-44-34 mp4_20230529_115134](https://github.com/sethyuan/logseq-plugin-smart-typing/assets/52104515/bb7d11ff-f809-4db5-b169-c8e697a75642)
