### ISSUE TITLE
[FEATURE REQUEST] Trigger regex replacement without space

### ISSUE THREAD

**Issue by JosephASullivan** [sethyuan/logseq-plugin-smart-typing#3]
Hi! First off I want to say that smart-typing is my favorite Logseq plugin. I like [Espanso](https://espanso.org/), but smart-typing is more convenient for Logseq than an app-specific Espanso configuration, and has some neat Logseq-specific features. Keep up the great work!

I was happy to see the new update that added regex functionality. However, currently you have to type a space at the end of an expression in order to activate a regex replacement. I think this feature would be more powerful and flexible if it triggered without having to hit the space bar. There are many use cases where a user will want a regex replacement to trigger where they wouldn't normally hit the space bar (for example, in the last word of a block immediately before hitting return/enter).

The currently implementation also introduces a bug. Here's an example to demonstrate it. Say that my `logseq-smart-typing.json` file has the following setting:
```
"trigger1": "you.me   ",
  "replacement1": "us",
```
if I type "you&me!!! " into Logseq (with the space at the end to trigger the Regex replacement), smart-typing will replace it with "youus". In other words, it will fail to delete the first `x` charcters of the original string, with `x` being the number of characters in the string between the end of the regex trigger and the space that triggers replacement. So "you&melvin " yields "you&us", "igotyourmessagetoday " yields "igotyourmessagus", etc.

The proposed change would resolve this issue. I will open a pull request to implement it!

**Comment by sethyuan** [comment]
Glad you like the plugin!

Regarding the space triggered design for regex, it helps improve the overall performance. Without a special trigger character, the regex would've being evaluated on each typing, however a match is rare in terms of probability.  That's why I'd prefer to leave this "spaced triggered" design intact.

As for the bad replacement, I can fix that.

**Comment by sethyuan** [comment]
FYI, the replacement issue is fixed. A new version is released.

**Comment by JosephASullivan** [comment]
Thanks for the explanation and the fix!
