### ISSUE TITLE
求支持中文输入法下， ～～删除线～～ 的支持！

### ISSUE THREAD

**Issue by hillsmao** [sethyuan/logseq-plugin-smart-typing#5]
这已经是我最爱的插件了，没有之一！之前给官方提交过很多issus ，像 ：： 的支持，`` 的支持，这里都支持了！能否再支持下中文输入法的删除线？ 不甚感激！

**Comment by sethyuan** [comment]
😀 实现了，试试新版本呢。

**Comment by hillsmao** [comment]
哇哦～so fast so cool！
