### ISSUE TITLE
大神！block文本中间的自动补全，指针会自动跳到block末尾！

### ISSUE THREAD

**Issue by hillsmao** [sethyuan/logseq-plugin-smart-typing#6]
当我在一行的中间，或者这一行有property ，我敲【【】】 它好像会把后面的内容都框起来……

![屏幕录制2023-02-22 14 23 53](https://user-images.githubusercontent.com/107061250/220540452-bbeb1062-d749-49f8-9c97-b377f97bd662.gif)

**Comment by hillsmao** [comment]
建议还是把 【【】】 和 （（）） 这两个官方已经支持的功能给关了？

**Comment by hillsmao** [comment]
：： 也出现了问题，发现只要是block内文本中间启用自动补全，指针自动就会跳到末尾。

**Comment by sethyuan** [comment]
：：的问题我重现了，【【的偶尔能出现没有补完的情况，但这两个又不是每次都能重现，只是有概率。起因是和Logseq的处理的互相干扰。感觉不太好解决，我再想想。

**Comment by hillsmao** [comment]
大神啊，这几天用，不停的打开再启用，我重度使用 replacement这个功能，但是 自动补全bug不停的跳，真是难受啊。

**Comment by sethyuan** [comment]
我看看做个开关把这两个功能去掉呢。

**Comment by hillsmao** [comment]
好的，感谢！

**Comment by sethyuan** [comment]
开关已加。

**Comment by hillsmao** [comment]
可以了！
