### ISSUE TITLE
大佬，求助，假设今天周三，我想打出后天，大后天，大大后天，下周六，替换具体的日期，有办法做到吗？

### ISSUE THREAD

**Issue by hillsmao** [sethyuan/logseq-plugin-smart-typing#8]

**Comment by sethyuan** [comment]
多建几个规则，每个都给不同的参数。
`{{date(1)}}`
`{{date(2)}}`
`{{date(3)}}`
以此类推，具体内置函数可参看README。

**Comment by hillsmao** [comment]
这个我知道

我想说有没有办法根据我当前的星期几，自动化？

例如：今天是周一，我写下周五   就自动根据今天的日期 {{date(4)}}

今天是周三，我写下周五，就自动根据今天的日期 {{date(2)}}

我想说有没有正则表达或者js可以做到这一点

**Comment by sethyuan** [comment]
哦，明白了。你可以用JS写个自定义函数来实现。至于代码是怎样的，这个要看你会不会编程了，也许可以AI辅助一下？

自定义函数的用户README里也有。

**Comment by hillsmao** [comment]
好的大佬

**Comment by sethyuan** [comment]
@hillsmao 我写了个示例用户函数，没有加在插件里，但可以做为用户函数使用。

```js
async function nextDate(day) {
  const today = new Date()
  const dayDiff = (day - today.getDay() + 7) % 7
  return date(dayDiff)
}
```

**Comment by hillsmao** [comment]
感谢感谢！！我是一点代码都不懂，只懂点css

**Comment by hillsmao** [comment]
> @hillsmao 我写了个示例用户函数，没有加在插件里，但可以做为用户函数使用。
> 
> ```js
> async function nextDate(day) {
>   const today = new Date()
>   const dayDiff = (day - today.getDay() + 7) % 7
>   return await date(dayDiff)
> }
> ```
> 
> 周日是0，周一是1，以此类推。

是这样填吗？，“周日是0，周一是1，” 这个填在哪？

<img width="545" alt="image" src="https://user-images.githubusercontent.com/107061250/222310996-2f2dcab5-8d93-4989-97f0-08da62aa1826.png">

**Comment by sethyuan** [comment]
不是这样哈，在第一个演示视频的后半段有演示用户自定义函数的使用。简单来说就是你随便找个页面把这个函数代码写到code里，再给这个块加个 `#.fn` 的标签，执行命令里的“重载加载用户函数“（或者重启Logseq）就能用了。使用用户函数的方法和使用内置函数的方法一样，就是replacement里写类似这样一段：`{{nextDate(0)}}`

**Comment by hillsmao** [comment]
太帅，太方便了！

**Comment by hillsmao** [comment]
好像没效果？我前面设置的日期也不能用了

<img width="708" alt="image" src="https://user-images.githubusercontent.com/107061250/222339703-884b5a28-7c93-404d-a5e4-ccef7f6cf5f5.png">
<img width="562" alt="image" src="https://user-images.githubusercontent.com/107061250/222339760-8b281513-b9aa-4c07-9faa-53f8cedb31c2.png">
<img width="613" alt="image" src="https://user-images.githubusercontent.com/107061250/222339804-3b0b611b-ff33-4090-8272-62ed3f209e2e.png">

**Comment by sethyuan** [comment]
我这边试了下是对的，你重启下Logseq看看呢。还不行看下console，看是什么错。

**Comment by hillsmao** [comment]
可以了，原来要放到page里去
